name: pre-build
on: [push, pull_request]
jobs:
  lua-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: luacheck-linter
        id: luacheck-linter
        uses: lunarmodules/luacheck@v1
        continue-on-error: true
        with:
          args: . --no-global --no-unused --no-redefined --no-unused-args --no-max-line-length --ignore 611 612 613 614; echo "lua-lint-result=$?" >> $GITHUB_OUTPUT
      - name: Check lua errors
        run: |
            echo "luacheck exit code was ${{ steps.luacheck-linter.outputs.lua-lint-result }}"
            if [ ${{ steps.luacheck-linter.outputs.lua-lint-result }} -eq 1 ]; then echo "Luacheck found warnings but no errors. Allowed to continue."; exit 0; fi; exit 1
  py-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Generator/requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --disable=R,C $(git ls-files '*.py')